version: "3"
services: 
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    tty: true 
    ports:
      - 8102:8102
    networks:
      - makuhari_city

networks:
  makuhari_city:
    external: true
