version: "3"
services: 
  liquid: 
    build:
      context: .
      dockerfile: Dockerfile
    tty: true 
    ports:
      - 8281:8281
    networks:
      - makuhari_city
networks:
  makuhari_city:
    external: true
